### PR TITLE
Updates node-amqp from 0.1.7 to 0.1.8 due to EventEmitter issue in 0.1.7

### PR DESCRIPTION
**Pull request by jonahharris**

### CODE REVIEW

**Comment by jonahharris** [comment]
Having used node-amqp extensively, I never trust any release without significant testing. When I find a version that works, I stick with it until I find another stable version. The number of times I've had to revert to a previous version because of bugs in the current release are too many to count :(

**Comment by robraux** [comment]
Ah. I see. :frowning:

**Comment by jonahharris** [comment]
Indeed. It sucks. Unfortunately, even with its issues, I haven't found the alternate library, amqplib, to be as good. Not yet, at least.

**Comment by demchenkoe** [comment]
I closed this pull request.
Already updated version node-amqp from 0.1.7 to 0.2.0.
Fixed incompatibility node-amqp version newer than 0.1.7
Leave fixity version "0.2.0" in package.json (instead of "~ 0.2.0") 
to avoid unforeseen problems at the next update node-amqp

**Pull request closed without merging**
